### ISSUE TITLE
Link Old LeechBlock to LeechBlog NG on Mozilla Addon Website

### ISSUE THREAD

**Issue by Miserlou** [proginosko/LeechBlock#20]
As of today, LeechBlock is dead on Firefox. :(

https://addons.mozilla.org/en-US/firefox/addon/leechblock/

I love LB, can you update it to make it WebExtention compatible?

**Comment by Miserlou** [comment]
Oh! I just discovered LeechBlock NG! Hooray!

So - my recommendation would be to have the page for LeechBlock mention LeechBlock NG!

**Comment by proginosko** [comment]
Good recommendation! I'll take care of it.
