### ISSUE TITLE
Access code font issues

### ISSUE THREAD

**Issue by ghost** [proginosko/LeechBlock#25]
Issue 1:
- The lowercase letter 'l' and the number '1' in the current font is indistinguishable.
- Also make it so uppercase "I" and "l" will be distinguishable if fix is applied.

Issue 2:
- Users can just inspect the element and copy paste the code without having to type it.

**Comment by proginosko** [comment]
Issue 1 has already been addressed. The access code can include '1' but not lowercase 'l' or uppercase 'I'.

Issue 2 has been addressed by adding the "Display access code as image" option (under General tab).
