### ISSUE TITLE
Consider adding in Readme info is it an abandoned, archived and replaced with NG or what

### ISSUE THREAD

**Issue by matkoniecz** [proginosko/LeechBlock#26]
Relation to https://github.com/proginosko/LeechBlockNG is unclear based on repo description.

I think that it is replaced and no longer maintained but I am not sure which one is place where I should report bugs.

Maybe https://github.com/proginosko/LeechBlock should be put in archive mode and get info in readme that it is replaced by https://github.com/proginosko/LeechBlockNG ?

**Comment by proginosko** [comment]
Yes, this legacy version is no longer maintained or supported. I will put a note in the README.
