### ISSUE TITLE
Delay page sometimes redirects to earlier page instead of target page

### ISSUE THREAD

**Issue by benwr** [proginosko/LeechBlock#27]
Occasionally (~ once every 20 times it's triggered), the delay page will open targeting the page I _left_ rather than the page I'm trying to _open_.

It might be that it happens more often when sites use weird redirect tricks (like Facebook exit links), but it also sometimes happens even when I type a URL directly into the URL bar.

**Comment by proginosko** [comment]
Thanks for this. This GitHub repository is for the legacy version of LeechBlock. Are you using that rather than the newer LeechBlock NG? If the latter, please repost here:

https://github.com/proginosko/LeechBlockNG/issues

**Comment by benwr** [comment]
Ah, whoops, thanks!
