### ISSUE TITLE
Timer Pauses When Tabbed Out

### ISSUE THREAD

**Issue by grantwforsythe** [proginosko/LeechBlock#28]
I have been using the extension for a while now and only recently noticed this _potential_ issue. 

If I tab out while on a restricted site, the timer will pause and the countdown will only resume if I tabbed back into the tab. 

 Is this an intended feature? 

I use the extension on `Firefox` which is currently updated to the latest version, `88.0`.

**Comment by proginosko** [comment]
Thanks for the report. Can you explain what you mean by "tab out" and "tab back"? Not sure what you're referring to.

**Comment by grantwforsythe** [comment]
Apologies, I should have been more clear in my initial comment. If I have a restricted tab open, the timer will only begin counting down if the cursor is _physically_ on the web page.

> Can you explain what you mean by "tab out" and "tab back"?

I was referring to the command `ALT+TAB` to navigate various applications at once. In this [example](https://gyazo.com/092795ab4b8ca28d51fef38b6ea6c220), I have Reddit opened on a second monitor. If I am switching between monitors or other applications on the same monitor, it will only begin counting down again if I physically click the webpage.

Additionally, if I am switching between tabs, it will only count down if my cursor is on the webpage - even though the webpage has been open for a longer period of time. ([Here](https://gyazo.com/04c39ccef1dfad3e70b30eefe1e5a1fd) is a visual).

**Comment by proginosko** [comment]
Sorry for the delay in replying. Have you tried selecting the option "Treat browser windows as always focused" (under General options)?

**Comment by grantwforsythe** [comment]
I tried as you suggested and the issue still persists.

**Comment by proginosko** [comment]
If the focus moves off the web page (e.g., to the location bar) then the time will not be counted. The workaround would be to deselect "Count time spent on these sites only when browser tab is active".

**Comment by grantwforsythe** [comment]
That works!
