### ISSUE TITLE
Tabs focus not working 

### ISSUE THREAD

**Issue by Harfho** [proginosko/LeechBlock#29]
After enabling Treat browser windows as always focused in LeechBlock General setting to keep delay timer counting after unfocus a tab to focus on another tab. 

its does not work or am I doing it wrong?.

what I wanted is after blocking a site using the delay page.
I what to be able to switch to another tab and still keep the delay countdown to keep counting.

**Comment by proginosko** [comment]
This is the repository for the legacy version of LeechBlock, which has been superseded by LeechBlock NG (https://github.com/proginosko/LeechBlockNG). This version is no longer under development.
