### ISSUE TITLE
Override doesn't work

### ISSUE THREAD

**Issue by lucafossen** [proginosko/LeechBlock#30]
When I activate an override, any site on my block list will still get blocked (screenshot attatched).
![image](https://user-images.githubusercontent.com/62906154/154503281-2cbc17ef-1f95-41ad-9bb9-8a896b250dd5.png)
Am I doing something wrong?
Running latest Firefox version.
Thanks!

**Comment by proginosko** [comment]
Did you select the option "Allow temporary override for these sites" for the relevant block set?

**Comment by lucafossen** [comment]
Thank you! I missed the option. It works great now
