### ISSUE TITLE
Block index page only

### ISSUE THREAD

**Issue by CyberShadow** [proginosko/LeechBlock#9]
Hi,

Is it possible to block only the index page of a website?

E.g. block 

https://news.ycombinator.com/ 

but not 

https://news.ycombinator.com/item?id=11749010

**Comment by proginosko** [comment]
Yes, but it can be a bit tricky. In your example, you'd do it like this:

news.ycombinator.com
+news.ycombinator.com/item**

The first line blocks the entire site, then the second line adds the non-index pages as an exception. See the LeechBlock website for more info on exceptions and wildcards.

**Comment by CyberShadow** [comment]
Excellent, thanks! Perhaps this can be added to the examples page at http://www.proginosko.com/leechblock/examples/ .

**Comment by proginosko** [comment]
Good suggestion.
